nav:
  Home: /
  About: /about/
  Writing: /posts/
  Projects: http://github.com/kendallcorner

projects_url: http://github.com/kendallcorner

customize:
    gravatar:
        email: kmwerts@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: true
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: true
      android:
        url: /images/favicon-192x192.png
        gravatar: true
      apple:
        url: /images/apple-touch-icon.png
        gravatar: false
    social_links:
        github: https://github.com/kendallcorner
        twitter: https://twitter.com/kendallcorner
        linkedin: https://www.linkedin.com/in/kendallwerts/
    show_all_posts: false
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-33031016-1

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
